project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  output-dir: docs   

website:
  title: "EC 390 - Development Econ"
  favicon: images/UO-icon.png
  navbar:
    right:
      - href: Lectures/list.qmd 
        text: Lectures
      - href: Readings/list.qmd
        text: Readings
      - href: Assignments/list.qmd
        text: Homework
      - href: Assignments/final-project.qmd
        text: Final Project
        
  announcement: 
    icon: clipboard2-check-fill
    dismissable: true
    content: "Week 04!!"
    type: warning
    position: below-navbar

format:
  html:
    theme: 
      - cosmo 
      - styles.scss
    toc: false