---
title: Assignments
---

## Problem Sets

[Problem Set 01]{.text-center .h .large .align-center} 

::: {.align-center}
[PS01 Questions](Problem-Sets/PS01/ps01.pdf){target=_blank .btn .btn-primary .btn-lg .cv-download}
::: 

---

[Problem Set 02]{.text-center .h .large .align-center} 

::: {.align-center}
[PS02 Questions](Problem-Sets/PS02/ps02.pdf){target=_blank .btn .btn-primary .btn-lg .cv-download} 
:::
---

[Problem Set 03]{.text-center .h .large .align-center} 


::: {.align-center}
[PS03 Questions](Problem-Sets/PS03/ps03.pdf){target=_blank .btn .btn-primary .btn-lg .cv-download}
:::

---

[Problem Set 04]{.text-center .h .large .align-center} 

::: {.align-center}
[PS04 Questions](Problem-Sets/PS04/ps04.pdf){target=_blank .btn .btn-primary .btn-lg .cv-download}
:::

---

## Exams

::: {.align-center}
[Fall 2025 Midterm Answer Key](Midterm/midterm-answer-key.pdf){target=_blank .btn .btn-primary .btn-lg .cv-download}
:::

---

## Quizzes

::: {.callout-note collapse="true"}
## Quiz 01 - Respond to the Prompt Below

There is no single 'silver bullet' that can solve the challenges of development.

**But if you had to choose one factor—whether a policy, institution, technology, or social change—that you believe would make the biggest difference in improving economic outcomes in developing countries, what would it be? Explain your reasoning**.
:::

---

::: {.callout-note collapse="true"}
## Quiz 02 - Respond to the Prompt Below

The Solow Growth Model predicts that economies will converge to a **steady state determined by savings, population growth and capital depreciation**. 
Yet some countries remain trapped in persistent low-growth equilibria. 

> How do you think that coordination failures can prevent an economy from reaching the "steady state growth path"? Why is large scale coordination difficult (think about individual incentives)?
:::


---

::: {.callout-note collapse="true"}
## Quiz 03 - Respond to the Prompt Below

We have talked about how education has its benefits and costs, and that it ultimately is worth it (when possible).

Think about your own decision to pursue higher education.

What trade-offs did you or your family face in making that decision?

What would it take for it to "pay-off" for you?
:::


---

::: {.callout-note collapse="true"}
## Quiz 04 - Respond to the Prompt Below

In recent times, we have seen a significant movement against globalization. Societal preferences have largely swung against foreign aid, free trade, and immigration. 

At the same time, these factors are significantly correlated with each other. Where greater and more efficient foreign aid may diminish immigration numbers as the origin country provides a better opportunity for growth. This makes these observed shifts in preferences complex and paradoxical.

Foreign aid often aims to reduce poverty and create jobs in developing countries, while migration allows individuals to seek better opportunities abroad.

Do these two forces **complement or substitute** each other in promoting development? How should we think about immigration as we face **population crises across developed nations**?
:::

---